import Head from 'next/head'
import { getSession } from 'next-auth/client'
import Header from '../components/Header'
import Login from './../components/Login';
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';
import Widgets from '../components/Widgets';
import { db } from '../firebase';

const Home = ({ session, posts }) => {
	console.log(posts);
	if(!session) return <Login />
	return (
		<div className="h-screen bg-gray-100 overflow-hidden">
			<Head>
				<title>Facebook</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/facebook.ico" />
			</Head>

			<Header/>

			<main className="flex over">
				<Sidebar />
				<Feed posts={posts} />
				<Widgets />
			</main>
		</div>
	)
}
export default Home


export async function getServerSideProps(context) {
	// Get the user
	const session = await getSession(context)
	//Get the posts
	const posts = await db.collection('posts').orderBy('timestamp', 'desc').get()
	const docs = posts.docs.map(p => ({
		id: p.id,
		...p.data(),
		postImage: null,
		timestamp: null
	}))

	return {
		props: {
			session,
			posts:docs
		}
	}
}